name: Build switch-updater

on: 
  push:
  workflow_dispatch:

jobs:
  SwitchBros-updater:
    runs-on: ubuntu-latest
    #container: hamletdufromage/devkita64_devkitarm
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v1

    - name: update repo
      run: |
        git config --global --add safe.directory /__w/switchbros-updater/switchbros-updater/lib/borealis
        git config --global --add safe.directory /__w/switchbrosh-updater/switchbros-updater
        git config --global --add safe.directory /__w/switchbros-updater/switchbros-updater/sbu-rcm
        git submodule update --init --recursive
        
    - name: Building switchbros-updater
      run: |
        make -C sbu-forwarder -f Makefile
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: switchbros-updater
        path: switchbros-updater.nro
