name: Build SwitchBros-updater

on: 
  push:
  workflow_dispatch:

jobs:
  AIO-switch-updater:
    runs-on: ubuntu-latest
    #container: hamletdufromage/devkita64_devkitarm
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v1

    - name: update repo
      run: |
        git submodule update --init --recursive
        
    - name: Building switchbros-updater
      run: |
        make -C aiosu-forwarder -f Makefile
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: switchbros-updater
        path: switchbros-updater.nro
